class BodyWorkout {
  final int id;
  final String name;
  final String imageAddress;
  final String description;
  final String workoutReps;

  BodyWorkout(
    {
    required this.id,
    required this.name,
    required this.imageAddress,
    required this.description,
    required this.workoutReps,
     
    }
  );
}

class InAppDatabase {
  static List<BodyWorkout> get bodyWorkouts {
    return [
      BodyWorkout(
        id: 1,
        name: 'Bench press',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/iJoG8dFpdxMyyFvhJcDyG8-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and back and triceps. Lie on a flat bench, holding a barbell with your hands slightly wider than shoulder-width apart using an overhand grip. Brace your core and press your feet into the ground, then lower the bar towards your chest. Press it back up to the start.',
        workoutReps: 'Sets 8 Reps 8 Rest 30sec',
      ),
      BodyWorkout(
        id: 2,
        name: 'Chin-up',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/5BZLNGFFZTmpKsNtGxvfBK-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and back. Hold a chin-up bar using a shoulder-width underhand grip. Brace your core, then pull yourself up until your chin is higher than the bar, keeping your elbows tucked in to your body. Lower until your arms are straight again.',
        workoutReps: 'Sets 3 Reps 6 Rest 20sec',
      ),
      BodyWorkout(
        id: 3,
        name: 'Bent-over row',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/B3PER8eUAMdSvduRoB4X8N-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and back. Hold a barbell using a shoulder-width overhand grip, hands just outside your legs. Bend your knees slightly, then bend forwards, hingeing from the hips and keeping your shoulder blades back. Pull the bar up towards your sternum, leading with your elbows, then lower it back to the start.',
        workoutReps: 'Sets 8 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 4,
        name: 'Diamond press-up',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/P7DzQQPrpLmwxHrA4oQQoK-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and back and triceps. Start in a press-up position but with your thumbs and index fingers touching to form a diamond. Keeping your hips up and core braced, bend your elbows to lower your chest towards the floor. Push down through your hands to return to the start.',
        workoutReps: 'Sets 3 Reps 12 Rest 60sec',
      ),
      BodyWorkout(
        id: 5,
        name: 'Incline flye',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/rhw3EMMY96jvSPgafmojC6-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and back. Lie on an incline bench holding a dumbbell in each hand above your face, with your palms facing and a slight bend in your elbows. Lower them to the sides, then bring them back to the top.',
        workoutReps: 'Sets 3 Reps 8 Rest 20sec',
      ),
      BodyWorkout(
        id: 6,
        name: 'Barbell high pull',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/7n6yvoR2NspJyqjQXfXyHA-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the shoulders. Stand tall with your feet shoulder-width apart, holding a barbell with an overhand grip and arms straight. Keeping your chest up and core braced, pull the bar upwards, leading with your elbows, until it reaches chin height. Then lower it back to the start.',
        workoutReps: 'Sets 3 Reps 8 Rest 20sec',
      ),
      BodyWorkout(
        id: 7,
        name: 'Lateral raise',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/3fLAawkKqojduwMkhRpKmH-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the shoulders. Stand tall, holding a light dumbbell in each hand by your sides, palms facing each other. Keeping your chest up, your core braced and a slight bend in your elbows, raise the weights out to shoulder height. Turn your thumbs down at the top, then lower them back to the start.',
        workoutReps: 'Sets 3 Reps 12 Rest 60sec',
      ),
      BodyWorkout(
        id: 8,
        name: 'Overhead press',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/NkMSiUhEKpdhLtSncfs9Jg-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the shoulders. Stand tall with your feet shoulder-width apart, holding a barbell across the top of your chest with hands slightly wider than shoulder-width apart. Keeping your chest up and core braced, press the bar overhead until your arms are straight, then lower it back to the start.',
        workoutReps: 'Sets 8 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 9,
        name: 'Seated dumbbell overhead press',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/TLmLUNCKHCT6mxgRTVUTLd-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and triceps. Sit on an upright bench holding a dumbbell in each hand at shoulder height, palms facing forwards. Keeping your chest up, press the weights directly overhead until your arms are straight, then lower them back to the start.',
        workoutReps: 'Sets 8 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 10,
        name: 'Hammer press',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/MaikPgkUrLzXDaBhojRctk-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and triceps. Lie on a flat bench, holding dumbbells by your shoulders with palms facing. Drive your feet into the floor and press the weights straight up, then lower them slowly back to the start.',
        workoutReps: 'Sets 3 Reps 6 Rest 20sec',
      ),
      BodyWorkout(
        id: 11,
        name: 'Dumbbell triceps extension',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/KDyiQ9Z2R5wq89QY6tTJm6-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the chest and triceps. Stand tall holding a dumbbell in each hand over your head, arms straight. Keeping your chest up, core braced and elbows pointing up, lower the weights behind your head, then return to the start.',
        workoutReps: 'Sets 3 Reps 8 Rest 20sec',
      ),
      BodyWorkout(
        id: 12,
        name: 'Pull-up',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/aQeRR3N3xgnsS6hKnzMEHN-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back and biceps. Hold a pull-up bar using an overhand grip with hands slightly wider than shoulder-width apart. Brace your core, then pull yourself up until your lower chest touches the bar. Lower until your arms are straight again.',
        workoutReps: 'Sets 8 Reps 8 Rest 30sec',
      ),
      BodyWorkout(
        id: 13,
        name: 'Barbell biceps curl',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/c5683RMnCGpJZrRb9MCTKV-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back and biceps. Hold a barbell with your hands shoulder-width apart using an underhand grip. Keeping your chest up, core braced and elbows tucked in to your sides, curl the bar up to your chest, squeezing your biceps as you go. Lower it back to the start.',
        workoutReps: 'Sets 8 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 14,
        name: 'Dumbbell curl',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/SXBDQPDmievxPpqJw6xHY8-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back and biceps. Hold dumbbells by your sides with straight arms, palms facing forwards. Keeping your chest up, core braced and elbows tucked in to your sides, curl the weights up, squeezing your biceps as you go. Then lower them back to the start.',
        workoutReps: 'Sets 3 Reps 12 Rest 60sec',
      ),
      BodyWorkout(
        id: 15,
        name: 'Reverse-grip bent-over row',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/L3naaw97SHEqwutHBgrzqm-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back and biceps. Hold a bar using a shoulder-width underhand grip, hands just outside your legs. Bend your knees slightly, then bend forwards, hingeing at the hips and keeping your shoulder blades back. Pull the bar up towards your sternum, leading with your elbows, then lower it back to the start.',
        workoutReps: 'Sets 3 Reps 8 Rest 30sec',
      ),
      BodyWorkout(
        id: 16,
        name: 'Dumbbell crunch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/Riw5xFsDUgM92BNBwTg38i-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the upper abs. Lie on your back, holding a dumbbell or weight plate across your chest in both hands. Raise your torso, then lower it, maintaining tension in your uppers abs throughout.',
        workoutReps: 'Reps 10 Rest 10sec',
      ),
      BodyWorkout(
        id: 17,
        name: 'Tuck and crunch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/E3m74sPpx6zBpER3MktUQ4-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the upper abs. Lie down with your hands by your head and your legs raised with your knees bent at a 90° angle. Simultaneously raise your torso and draw your knees towards your chest. Keep your fingers by your temples throughout and initiate each rep smoothly without jerking your torso up. Don’t let your feet touch the floor between reps.',
        workoutReps: 'Reps 15 Rest 10sec',
      ),
      BodyWorkout(
        id: 18,
        name: 'Modified V-sit',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/n9xpo5EK8u3t9TkhakJeEG-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the upper abs. Lie with your legs raised off the floor and extended away from you so they’re parallel with the floor, and your arms straight by your sides, held off the floor. Keep your arms straight as you raise your torso and bring your legs in, bending at the knees, so that your chest meets your knees at the top of the move. Then lower under control.',
        workoutReps: 'Reps 12 Rest 10sec',
      ),
      BodyWorkout(
        id: 19,
        name: 'Crunch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/SRCioY34h3TRm7mLMn6rKT-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back upper abs. Lie on your back with your knees bent and feet planted, and your arms crossed across your chest. Raise your torso using your abs, then lower. Your upper abs will already be close to fatigue but try to hold the top position of each rep for at least one second to make them work as hard as possible.',
        workoutReps: 'Reps 20 Rest 90sec',
      ),
      BodyWorkout(
        id: 20,
        name: 'Hanging leg raise',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/gDNfjY6QoFJRYLXKC2nCHi-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back lower abs. Fair warning, this tough exercise sets the tone for what is going to be a brutal workout involving four different hanging exercises. Start in a dead hang with your legs straight and your knees and ankles touching. Keep them together as your use your lower abs to raise them, then lower back to the start under control.',
        workoutReps: 'Reps 10 Rest 10sec',
      ),
      BodyWorkout(
        id: 21,
        name: 'Hanging knee raise twist',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/3mdteZp6Hmc6c4Y9h8ccr3-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back lower abs. Start in a dead hang with your legs straight and knees together. Twist your body and raise your knees to one side, then return to the start. Continue, alternating sides.',
        workoutReps: 'Reps 12 each side Rest 10sec',
      ),
      BodyWorkout(
        id: 22,
        name: 'Hanging knee raise',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/ySvoKjEqDtTnaGTvTKurEB-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back lower abs. This slightly easier variation on the hanging leg raise still puts a lot of pressure on your lower abs. Start in a dead hang and raise your knees powerfully to activate more of the muscle fibres in the lower abs. Lower back to the start under control to prevent swinging.',
        workoutReps: 'Reps 15 Rest 10sec',
      ),
      BodyWorkout(
        id: 23,
        name: 'Garhammer raise',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/QCnoQWraEAhCStBjDMmXaH-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back lower abs. Start hanging from the bar but with your knees already raised to around your midsection, then lift them as high as you can. Lower back to the start under control, keeping your abs engaged throughout.',
        workoutReps: 'Reps 20 Rest 90sec',
      ),
      BodyWorkout(
        id: 24,
        name: 'Decline plank with foot touch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/CPxycpb8NJhNviqXbhsc3Q-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back obliques and core. Get into a decline plank position, supporting yourself on your forearms with your feet raised on a bench. Your body should form a straight line from heels to head and the aim is to maintain that position throughout the exercise. Lift one foot off the bench and move it to the side to touch the floor, then return it to the bench. Continue, alternating sides.',
        workoutReps: 'Reps 10 each side Rest 10sec',
      ),
      BodyWorkout(
        id: 25,
        name: 'Seated Russian twist',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/oKvrdu8n8A9RKeffK5qA3V-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back obliques and core. Sit on the floor with your knees bent and heels on the ground. Your torso should be at the top of the crunch position, forming a 45° angle to the ground. Twist your torso from side to side, moving in a smooth and controlled manner.',
        workoutReps: 'Reps 12 each side Rest 10sec',
      ),
      BodyWorkout(
        id: 26,
        name: 'Bicycle crunches',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/RGWxkNgQuqY58yeGEXWC3b-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back obliques and core. Lie on your back with your hands by your temples and your legs raised with your knees bent at a 90° angle. Bring your right knee up towards your chest while raising your torso and twisting so your left elbow comes to meet your knee. Then lower and do the same on the opposite side. Keep your shoulders and feet off the ground to force your abs to work hard to stabilise your torso.',
        workoutReps: 'Reps 15 each side Rest 10sec',
      ),
      BodyWorkout(
        id: 27,
        name: 'Plank',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/SxC46BA6URjqmi2zg5NkSg-1200-80.jpg.webp',
        description: 'This movement has the greatest effect on the back obliques and core. Maintain a strict plank position, with your hips up, your glutes and core braced, and your head and neck relaxed. Breathing slowly and deeply, hold the position for as long as possible.',
        workoutReps: 'Time Max Rest 90sec',
      ),
      BodyWorkout(
        id: 28,
        name: 'Diagonal mountain climber',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/tR4BZeiBG7gxQUJ8ZNiyQk-1200-80.jpg.webp',
        description: 'Start in a press-up position. Without letting your hips sag, draw one knee in and bring it across towards the opposite elbow. Return to the start, then repeat with your other leg. Keep reps fast but controlled.',
        workoutReps: 'Sets 3 Reps 12 each side Rest 2min',
      ),
      BodyWorkout(
        id: 29,
        name: 'Knees-up crunch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/dNb22n2MriYug2Y92fQa9k-1200-80.jpg.webp',
        description: 'Lie on your back with your fingers at your temples, your knees bent and your feet up. Engage your upper abs to raise your torso off the ground, then crunch up to meet your knees. Lower slowly back to the start, keeping tension on your abs throughout.',
        workoutReps: 'Sets 3 Reps 12 Rest 0sec',
      ),
      BodyWorkout(
        id: 30,
        name: 'Reverse crunch',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/i5JzY9VBzRnkHW4TNshPj8-1200-80.jpg.webp',
        description: 'Lie flat on your back with your arms flat on the floor and knees bent. Use your lower abs to draw your knees in towards your chest, then raise your hips off the ground, Lower slowly back to the start, keeping your entire core engaged.',
        workoutReps: 'Sets 3 Reps 12 Rest 0sec',
      ),
      BodyWorkout(
        id: 31,
        name: 'Deadlift',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/AMQVNMyuWcTrHcLcE3XWrL-1200-80.jpg.webp',
        description: 'this movement has effect on all-over muscle. Stand tall with the barbell in front of you, then squat down and grasp it with an overhand grip. Keeping your chest up and core braced, press down through your heels to stand up. Push your hips forwards at the top, then lower.',
        workoutReps: 'Sets 5 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 32,
        name: 'Leg press',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/n7PiqSYiGLinW7aMdESmDW-1200-80.jpg.webp',
        description: 'this movement makes your quads and hamstrings hard and safely. Sit in the leg press machine positioned correctly according to the instructions. Place your feet lower and closer together to work your quads more, or higher and wider to hit your hamstrings and glutes more directly. Bend your knees to bring them towards your chest, then press back to the start.',
        workoutReps: 'Sets 5 Reps 8 Rest 60sec',
      ),
      BodyWorkout(
        id: 33,
        name: 'Seated hamstring curl',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/2UwkMkuqXPcQvzdXYyCgJg-1200-80.jpg.webp',
        description: 'this movement isolates the backs of your thighs to fatigue more muscle fibres. Position yourself correctly with your legs straight and the padded bar against your lower leg. Squeeze your hamstrings to bring your heels towards you, then return to the start.',
        workoutReps: 'Sets 4 Reps 10 Rest 30sec',
      ),
      BodyWorkout(
        id: 34,
        name: 'Seated leg extension',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/XunwRGtKYCvNqgLPneRfVo-1200-80.jpg.webp',
        description: 'this movement isolates your quads so you can go heavy. Position yourself correctly with your knees bent and the padded bar against your shins. Raise your feet to straighten your legs, then squeeze your quads at the top. Lower back to the start position slowly to increase the tension on the target muscles.',
        workoutReps: 'Sets 4 Reps 10 Rest 60sec',
      ),
      BodyWorkout(
        id: 35,
        name: 'Dumbbell lunge',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/584gxwqgqYjXG6MJr2r9fE-1200-80.jpg.webp',
        description: 'This movement works all your lower leg muscles as well as your abs and lower back .Stand tall, holding a dumbbell in each hand. With your chest up and core braced, take a big step forwards with your left leg and lunge down until both knees are bent at 90°. Push off your front foot to return to the start, then repeat with your right leg. Alternate your leading leg with each rep.',
        workoutReps: 'Sets 3 Reps 8 each side Rest 30sec',
      ),
      BodyWorkout(
        id: 36,
        name: 'Dumbbell squat',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/TDa6tAKjzwEfNB5kBS3bpN-1200-80.jpg.webp',
        description: 'This movement targets your glutes and abs as well as your quads and hams. Stand tall, holding a dumbbell in each hand. With your chest up and core braced, bend at your hips and knees to squat down as deep as you can without rounding your back. Push down through your heels to stand back up and return to the start position.',
        workoutReps: 'Sets 3 Reps 15 Rest 60sec',
      ),
      BodyWorkout(
        id: 37,
        name: 'Bulgarian split squat',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/f4aao8W3ck3EvZKKRsHkTF-1200-80.jpg.webp',
        description: 'You can use a barbell or hold a dumbbell in each hand for this leg day workout exercise, or use no weight at all if you’re finding it hard to maintain your balance. With the top of one foot resting on a bench, step forwards into a lunge with the other. Lower until your front thigh is parallel to the ground, then drive back up. Do all your reps on one leg, then swap sides.',
        workoutReps: 'Sets 3 Reps 10-12 each leg',
      ),
      BodyWorkout(
        id: 38,
        name: 'Cable kick-back',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/hJ2aa8764WR3gbRY9zDYQ-1200-80.jpg.webp',
        description: 'Attach an ankle cuff to the low pulley on a cable machine, or just slip your foot into a looped handle. Stand facing the machine and hold it with both hands. Slowly kick the attached leg back in an arc, taking it as high as it will comfortably go. Then bring it back down slowly. Do all your reps on one leg, then swap sides.',
        workoutReps: 'Sets 3 Reps 15-20 each leg',
      ),
      BodyWorkout(
        id: 39,
        name: 'Reverse barbell lunge',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/LTjc5VwaBnv4Sqrc2U33AY-1200-80.jpg.webp',
        description: 'Prop the barbell on the back of your shoulders. Step back with your right leg, bending your knee to approximately 90° (this will bring the front knee to a 90° bend as well). Keep your chest up and open, and engage your core. Stand up by pushing through your left leg and bringing your right leg back to the original standing position. Repeat for the other leg.',
        workoutReps: 'Set 4 Reps 8',
      ),
      BodyWorkout(
        id: 40,
        name: 'Side lunge',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/nQJrHMMBMej5eedS72QpZS-1200-80.jpg.webp',
        description: 'This movement targets Abductors. From standing take a big step to one side and lower until the knee on your leading leg is bent at 90°, keeping your trailing leg straight. Push back up to standing. Do all your reps on one side, then switch.',
        workoutReps: 'Sets 3 Reps 10 each side',
      ),
      BodyWorkout(
        id: 41,
        name: 'Dumbbell goblet squat',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/pPvXWB6R5m4FgYRGBEGqya-1200-80.jpg.webp',
        description: 'Stand with your feet hip-width apart and your toes pointed out at a 45° angle, holding a dumbbell in both hands by your chest. Drop into a deep squat, then drive back up.',
        workoutReps: 'Sets 3 Reps 12',
      ),
      BodyWorkout(
        id: 42,
        name: 'Lunge',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/fSEYW4GYqRddMRk8dsv9VS-1200-80.jpg.webp',
        description: 'This movement targets Quads, hamstrings and glutes. From standing, take a big step forwards with your right foot and lower until both your knees are bent at 90°. Push back up through your right foot to standing. Do all your reps on one leg, then switch to the other.',
        workoutReps: 'Sets 3 Reps 10 each side',
      ),
      BodyWorkout(
        id: 43,
        name: 'Donkey kick',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/Qjvwkhy85Lzn4tPVfjh8JS-1200-80.jpg.webp',
        description: 'This movement targets Hamstrings and glutes. Get on all fours with your hands under your shoulders and your knees on the floor under your hips. Engage your core and lift one leg behind you, keeping your knee bent so the sole of your foot ends up facing the ceiling. Bring your leg back down slowly. Do all your reps on one leg, then switch.',
        workoutReps: 'Sets 3 Reps 10 each side',
      ),
      BodyWorkout(
        id: 44,
        name: 'Calf raise',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/xmX8Fz5WtSr4Yw6KHRsofe-1200-80.jpg.webp',
        description: 'This movement targets Hamstrings and glutes. From standing, raise your heels off the ground until you are standing on your toes, then lower under control.',
        workoutReps: 'Sets 3 Reps 10',
      ),
      BodyWorkout(
        id: 45,
        name: 'Wall sit',
        imageAddress: 'https://cdn.mos.cms.futurecdn.net/xrenHouUqucF32hq4gne2E-1200-80.jpg.webp',
        description: 'Stand near a wall (around two feet away). Lean back against the wall with your torso, with your feet shoulder-width apart. Then press back and slide down the wall until your thighs are parallel with the ground. Your knees should be above your ankles and bent at right-angles. Keep your head, shoulders and upper back against the wall and hold the position.',
        workoutReps: 'Sets 3 Reps 30 secs Rest 10secs',
      ),
    ];
  }
}