// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjJClsmQUpIKHIjY_caBpTAIJXrOQRMw',
    appId: '1:752440138682:web:740667606352469dda5b83',
    messagingSenderId: '752440138682',
    projectId: 'workout-list-f3a22',
    authDomain: 'workout-list-f3a22.firebaseapp.com',
    storageBucket: 'workout-list-f3a22.appspot.com',
    measurementId: 'G-GBCBKRFRP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqFuezGf28-fftyCDvQPQBt51B4chc-U',
    appId: '1:752440138682:android:137d2ec730e867e7da5b83',
    messagingSenderId: '752440138682',
    projectId: 'workout-list-f3a22',
    storageBucket: 'workout-list-f3a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAYcaybZLOPIMuEcBYgazePPtnJM_zKnI',
    appId: '1:752440138682:ios:12298315010ba8aeda5b83',
    messagingSenderId: '752440138682',
    projectId: 'workout-list-f3a22',
    storageBucket: 'workout-list-f3a22.appspot.com',
    iosClientId: '752440138682-luld50u24umr2h4ort7kc288ji6avoa9.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAYcaybZLOPIMuEcBYgazePPtnJM_zKnI',
    appId: '1:752440138682:ios:b5f36c97a4915d1dda5b83',
    messagingSenderId: '752440138682',
    projectId: 'workout-list-f3a22',
    storageBucket: 'workout-list-f3a22.appspot.com',
    iosClientId: '752440138682-g1skri2ptedtkpt7ghdl274rgu27m206.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutList.RunnerTests',
  );
}
